### PR TITLE
Added a filter

### PR DESCRIPTION
**Pull request by bitflower**
Hey dude :-)

I have extended you plugin again.

I have added the "media" filter to simply retrieve the matching rule.
It also takes some options to "group" several rule names together.

See updated readme for examples.

Cheers!

### CODE REVIEW

**Comment by bitflower** [comment]
Just when creating the PR i thought it might be cleaner to have to filters: one that actually only retrieves the actual rule name and one that does the replace of the % sign.

Let me know your thoughts first.

Bye

**Comment by jacopotarantino** [comment]
This is pretty good work, thanks! I have a couple comments but could you rebase first? I don't want to comment on things that aren't actually a problem.

**Comment by bitflower** [comment]
Aww, you're right. Legt me fix this...

**Comment by bitflower** [comment]
I had a little fight with git so I'm closing the PR and opening a niew one. Hoping it'll turn out good...

**Pull request closed without merging**
