### PR TITLE
Extended default media queries & maintenance.

### PR DESCRIPTION
**Pull request by bitflower**
- jslinted (Sublime text gave me a lot errors)
- Changed standard resolutions to support 0-479px for really tiny screens
- replaced array detection code

### CODE REVIEW

**Comment by bitflower** [comment]
Hey, sorry for the delay!

I have reverted the default rules.

By "spacing" you mean the formatting of the code?

Cheers!

**Comment by bitflower** [comment]
I have changed the intendation to 2 spaces.

I have added a new method that only fires if the screen is actually the size of the given breakpoint. See updated doc for example.

Would love to PR this!

Bye

**Comment by jacopotarantino** [comment]
Thanks so much for keeping up with this. Also, I feel like I should apologize because I did not realize what a mess the spacing was in that file before. Super inconsistent.

Anyway, I'm on board with this. I'm going to merge it and make a few tweaks before I tag it for release.

**Comment by jacopotarantino** [comment]
Boom. 0.4.0 has your changes in it. Thanks for the contribution!

**Pull request merged**
